package com.landosol.toolbox.labyrinth.vision

import com.landosol.toolbox.clanbattle.recognition.BinaryImage
import com.landosol.toolbox.clanbattle.recognition.DigitMatchResult
import com.landosol.toolbox.clanbattle.recognition.PixelImage
import com.landosol.toolbox.clanbattle.recognition.StructuralMatcher
import kotlin.math.min
import kotlin.math.roundToInt

/**
 * Recognizes the small white 1-3 counters drawn over the compact map relic badges.
 *
 * These counters use a different outlined font from battle power/level digits. The pale panel to
 * their right also defeats ordinary dark-glyph Otsu binarization. We instead isolate bright
 * connected components that do not touch the crop edge: the panel and badge highlights touch an
 * edge, while the white interior of the outlined digit remains enclosed.
 */
object LabyrinthCompactCounterRecognizer {
    fun match(image: PixelImage): DigitMatchResult {
        val normalized = normalize(image)
        val ranking = TEMPLATES.map { (digit, template) ->
            RankedDigit(digit, StructuralMatcher.iou(normalized, template))
        }.sortedByDescending(RankedDigit::score)
        val best = ranking[0]
        val second = ranking[1]
        val third = ranking[2]
        val margin = best.score - second.score
        return DigitMatchResult(
            digit = best.digit,
            score = best.score,
            confidence = min(
                (best.score - 0.30) / 0.35,
                margin / 0.20,
            ).coerceIn(0.0, 1.0),
            margin = margin,
            secondDigit = second.digit,
            secondScore = second.score,
            thirdDigit = third.digit,
            thirdScore = third.score,
        )
    }

    internal fun normalize(image: PixelImage): BinaryImage {
        val raw = BooleanArray(image.pixels.size) { index ->
            val color = image.pixels[index]
            val red = color ushr 16 and 0xff
            val green = color ushr 8 and 0xff
            val blue = color and 0xff
            min(red, min(green, blue)) >= MIN_LIGHT_CHANNEL
        }
        val selected = largestEnclosedComponent(raw, image.width, image.height)
            ?: return EMPTY_NORMALIZED
        var left = image.width
        var top = image.height
        var right = -1
        var bottom = -1
        selected.indices.forEach { index ->
            if (!selected[index]) return@forEach
            val x = index % image.width
            val y = index / image.width
            if (x < left) left = x
            if (x > right) right = x
            if (y < top) top = y
            if (y > bottom) bottom = y
        }
        val sourceWidth = right - left + 1
        val sourceHeight = bottom - top + 1
        val available = CANVAS_SIZE - PADDING * 2
        val scale = min(available.toDouble() / sourceWidth, available.toDouble() / sourceHeight)
        val targetWidth = (sourceWidth * scale).roundToInt().coerceIn(1, available)
        val targetHeight = (sourceHeight * scale).roundToInt().coerceIn(1, available)
        val offsetX = (CANVAS_SIZE - targetWidth) / 2
        val offsetY = (CANVAS_SIZE - targetHeight) / 2
        val output = BooleanArray(CANVAS_SIZE * CANVAS_SIZE)
        repeat(targetHeight) { targetY ->
            val sourceY = top + targetY * sourceHeight / targetHeight
            repeat(targetWidth) { targetX ->
                val sourceX = left + targetX * sourceWidth / targetWidth
                if (selected[sourceY * image.width + sourceX]) {
                    output[(offsetY + targetY) * CANVAS_SIZE + offsetX + targetX] = true
                }
            }
        }
        return BinaryImage(CANVAS_SIZE, CANVAS_SIZE, output)
    }

    private fun largestEnclosedComponent(
        raw: BooleanArray,
        width: Int,
        height: Int,
    ): BooleanArray? {
        val visited = BooleanArray(raw.size)
        val queue = IntArray(raw.size)
        var best: IntArray? = null
        var bestSize = 0
        raw.indices.forEach { start ->
            if (!raw[start] || visited[start]) return@forEach
            var head = 0
            var tail = 0
            var touchesEdge = false
            queue[tail++] = start
            visited[start] = true
            while (head < tail) {
                val index = queue[head++]
                val x = index % width
                val y = index / width
                if (x == 0 || y == 0 || x == width - 1 || y == height - 1) touchesEdge = true
                fun enqueue(neighbor: Int) {
                    if (raw[neighbor] && !visited[neighbor]) {
                        visited[neighbor] = true
                        queue[tail++] = neighbor
                    }
                }
                if (x > 0) enqueue(index - 1)
                if (x + 1 < width) enqueue(index + 1)
                if (y > 0) enqueue(index - width)
                if (y + 1 < height) enqueue(index + width)
            }
            if (!touchesEdge && tail >= MIN_COMPONENT_AREA && tail > bestSize) {
                best = queue.copyOf(tail)
                bestSize = tail
            }
        }
        val indices = best ?: return null
        return BooleanArray(raw.size).also { selected ->
            indices.forEach { selected[it] = true }
        }
    }

    private fun pattern(value: String): BinaryImage {
        val rows = value.trimIndent().lines()
        require(rows.size == CANVAS_SIZE && rows.all { it.length == CANVAS_SIZE })
        return BinaryImage(
            CANVAS_SIZE,
            CANVAS_SIZE,
            BooleanArray(CANVAS_SIZE * CANVAS_SIZE) { index ->
                rows[index / CANVAS_SIZE][index % CANVAS_SIZE] == '#'
            },
        )
    }

    private data class RankedDigit(val digit: Int, val score: Double)

    private const val MIN_LIGHT_CHANNEL = 220
    private const val MIN_COMPONENT_AREA = 2
    private const val CANVAS_SIZE = 24
    private const val PADDING = 2
    private val EMPTY_NORMALIZED = BinaryImage(CANVAS_SIZE, CANVAS_SIZE, BooleanArray(CANVAS_SIZE * CANVAS_SIZE))

    // Derived from the real 1920x1080 map counter samples in Test_Screenshots. Only the enclosed
    // white glyph is retained, so badge colour and the surrounding pale panel are not templates.
    private val TEMPLATES = mapOf(
        1 to pattern(
            """
            ........................
            ........................
            .............#..........
            .............#..........
            .............#..........
            ............##..........
            .........#####..........
            ...........###..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ............##..........
            ........................
            ........................
            """,
        ),
        2 to pattern(
            """
            ........................
            ........................
            ...........####.........
            ...........####.........
            ...........####.........
            ...........####.........
            ...........####.........
            .............####.......
            .............####.......
            .............####.......
            .............####.......
            .............####.......
            .............####.......
            .............####.......
            .............####.......
            .............####.......
            ...........####.........
            ...........####.........
            .........######.........
            .........######.........
            ......#####.............
            ......#####.............
            ........................
            ........................
            """,
        ),
        3 to pattern(
            """
            ........................
            ........................
            ..............##........
            ..............##........
            ..............##........
            ..............####......
            ..............####......
            ................####....
            ................####....
            ................####....
            ................####....
            ................####....
            ................####....
            ................####....
            ................####....
            ................####....
            ..............####......
            ..............####......
            ...........#####........
            ...........#####........
            ....##########..........
            ....##########..........
            ........................
            ........................
            """,
        ),
    )
}
